version: "3"
services:
      
  grafana:
    container_name: grafana
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
      GF_PATHS_DATA: /var/lib/grafana
      GF_PATHS_HOME: /usr/share/grafana
      GF_PATHS_LOGS: /var/log/grafana
      GF_PATHS_PLUGINS: /var/lib/grafana/plugins
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      TZ: Europe/Berlin
    hostname: grafana
    image: grafana/grafana:8.4.6
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      # to be modified depending on your needs
      - ./grafana/data:/var/lib/grafana
      - ./grafana/etc/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3000 || exit 1"]
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

networks:
  default:
    name: monitoring
    driver: bridge
